train:
  _target_: src.datasets.AVSSDataset
  partition: train
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.AVSSDataset
  partition: val
  instance_transforms: ${transforms.instance_transforms.inference}
