device: "auto"
train:
  - _target_: src.metrics.PIT_SISNRi
    device: ${metrics.device}
    name: "si_snri"
inference:
  - _target_: src.metrics.PIT_SISNRi
    device: ${metrics.device}
    name: "si_snri"
  - _target_: src.metrics.PIT_SISDRi
    device: ${metrics.device}
    name: "si_sdri"
  - _target_: src.metrics.PIT_SISNR
    device: ${metrics.device}
    name: "si_snr"
  - _target_: src.metrics.PIT_PESQ
    sample_rate: 16000
    mode: 'wb' # WildBerries (TODO remove this joke)
    n_processes: 1
    device: ${metrics.device}
    name: "pesq"
  - _target_: src.metrics.PIT_STOI
    sample_rate: 16000
    device: ${metrics.device}
    name: "stoi"
