defaults:
  - metrics: pit
  - transforms: only_peak_normalization
  - dataloader: bs4
  - _self_

metric_calculator:
  device: auto
  gt_path: "data/avss_dataset_mini/audio/mini_train"
  pred_path: "data/mini_done/inf"
  seed: 1
