defaults:
  - model: rtfsnet_pit
  - metrics: pit
  - datasets: inf_av
  - dataloader: bs4
  - transforms: only_peak_normalization
  - _self_
video_encoder:
  prepare_embeddings: True
  weights_dir: "weights"
  model_name: "lrw_resnet18_dctcn_video_boundary"
  dataloader:
    _target_: torch.utils.data.DataLoader
    batch_size: 1
    num_workers: 0
    pin_memory: True
  dataset_path: null # provide path to your dataset with mouths

inferencer:
  device_tensors: ["target", "mix", "s1_video_emb", "s2_video_emb"]
  device: auto
  save_path: null # provide path to dir with results
  seed: 1
  from_pretrained: null # provide path to checkpoint
