defaults:
  - model: rtfsnet_pit
  - metrics: pit
  - datasets: inf
  - dataloader: bs4
  - transforms: only_peak_normalization
  - _self_
video_encoder:
  prepare_embeddings: True
  weights_dir: "weights"
  model_name: "lrw_resnet18_dctcn_video_boundary"
  dataloader:
    _target_: torch.utils.data.DataLoader
    batch_size: 1
    num_workers: 0
    pin_memory: True
  dataset_path: "data/avss_dataset_mini"

inferencer:
  device_tensors: ["target", "mix"]
  device: auto
  save_path: "data/mini_done"
  seed: 1
  from_pretrained: "saved/rtfsnet_bs8/model_best.pth"
