_target_: src.logger.CometMLWriter
project_name: "dla-avss"
workspace: null
run_name: "testing"
mode: "online"
loss_names: ["loss", "si_snr_loss", "complex_spec_loss"]
log_checkpoints: False
id_length: 32
